version: "3.7"

services:

  web:
    image: getumbrel/umbrel-nostr-relay
    build: .
    user: "1000:1000"
    restart: on-failure
    environment:
      RELAY_HOST: "192.168.141.237"  #change this to the local address of your relay
      RELAY_PORT: "8080"
    ports:
      - 3000:3000