version: "3.7"

services:

  web:
    image: miningsc/umbrel-nostr-relay-monitor
    build: .
    user: "1000:1000"
    restart: on-failure
    environment:
      RELAY_HOST: "172.17.0.5"  #change this to the local address of your relay
      RELAY_PORT: "8080"
    ports:
      - 3000:3000